increase resilience to rate limiting QUALITY-2043
dcos/dcos-launch pull request #134
Opened 2018-05-09 09:45 UTC by cprovencher

2018-05-09 22:57 UTC, sschneid requested changes

2018-05-09 22:57 UTC, sschneid commented on dcos_launch/aws.py
> +        while True:
Maybe have some sort of `max_try` to keep it from looping forever?

2018-05-09 22:59 UTC, sschneid commented
We're currently importing the [`retrying`](https://github.com/dcos/dcos-launch/blob/master/requirements.txt#L18) library, could this be used instead of constructing retry logic?

2018-05-10 00:53 UTC, cprovencher commented
@sschneid  I just added a maximum and also implemented the real exp backoff (random between 0 and 2^tries - 1) instead of what I had done (wrong as sleep time rises way too fast)

I would argue against using retrying in this case because it's cumbersome when you don't want to retry based on a result or an exception, but instead want to check 5 conditions and do an exponential backoff

2018-05-10 02:23 UTC, sschneid approved these changes
lgtm!

2018-05-10 03:14 UTC, margaret commented
I think this would be the equivalent way to do it with the lib, although I haven't tested it
```python
def get_onprem_cluster(self):
    num_masters = int(self.config['num_masters'])
    num_private_agents = int(self.config['num_private_agents'])
    num_public_agents = int(self.config['num_public_agents'])

    @retry(wait_exponential_multiplier=10 * 10000, wait_exponential_max=20*60*1000, retry_on_result=False)
    def _get_cluster():
        cluster = dcos_test_utils.onprem.OnpremCluster.from_hosts(
            bootstrap_host=self.get_bootstrap_host(),
            cluster_hosts=self.get_cluster_hosts(),
            num_masters=num_masters,
            num_private_agents=num_private_agents,
            num_public_agents=num_public_agents)

        num_masters_found = len(cluster.masters)
        num_private_agents_found = len(cluster.private_agents)
        num_public_agents_found = len(cluster.public_agents)
        bootstrap_host_found = bool(cluster.bootstrap_host)

        cluster_matches_config = num_masters_found == num_masters and num_private_agents_found == num_private_agents and \
            num_public_agents_found == num_public_agents and bootstrap_host_found

        if not cluster_matches_config:
            msg = ("Not all required hosts were found:\n"
                   "\tmaster count: expected {}, found {}\n"
                   "\tprivate agent count: expected {}, found {}\n"
                   "\tpublic agent count: expected {}, found {}\n"
                   "\tbootstrap host found: {}")
            msg = msg.format(num_masters, num_masters_found,
                             num_private_agents, num_private_agents_found,
                             num_public_agents, num_public_agents_found,
                             bootstrap_host_found)

            log.info("Stack not ready yet for DC/OS installation. " + msg)

        return cluster_matches_config

    return _get_cluster()
```

2018-05-10 20:32 UTC, cprovencher commented
@margaret you're right - my cumbersome argument is wrong, however the retrying lib doesn't do exponential backoff correctly - sleep time rises way too fast. All it does is 2^x where x is the number of tries. The correct way exponential backoff is implemented is random between 0 and 2^x - 1 where x is the number of tries

The way I figured out my previous code was wrong is not the result of any testing - I just hadn't implemented exponential backoff. I was doing 2x2=4   4x4=8 8x8=16 etc. which is even worse than 2^x

2018-05-15 00:35 UTC, cprovencher commented
@margaret  you win, using retrying is more consistent with the rest of the project and more readable

2018-05-15 03:42 UTC, merged