Use orchestratorRelease instead of orchestratorVersion
dcos/dcos-launch pull request #140
Opened 2018-05-16 13:29 UTC by ionutbalutoiu

Setting orchestratorRelease instead of orchestratorVersion will
make acs-engine use the latest DC/OS version for the major release
specified.

2018-05-16 19:44 UTC, sschneid approved these changes

2018-05-16 20:22 UTC, cprovencher requested changes
Ideally we should be able to pass this through the config

2018-05-18 14:09 UTC, ionutbalutoiu commented
@cprovencher, I'll make the change.

2018-05-18 16:58 UTC, ionutbalutoiu commented
@cprovencher, please see my updated PR with the requested change.

2018-05-25 16:33 UTC, margaret approved these changes

2018-05-25 18:08 UTC, cprovencher approved these changes

2018-05-25 18:10 UTC, merged