Fix install_prereqs: True bug
dcos/dcos-launch pull request #151
Opened 2018-06-08 22:19 UTC by cprovencher

## High-level description (required)

Allows the use of "install_prereqs: True" config param. Previously, when specifying this parameter, dcos-launch could not find the default install_prereqs.sh script

## Corresponding tickets (required)

These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

https://jira.mesosphere.com/browse/DCOS-35442

[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch&branch_DcosIo_DcosLaunch=%3Cdefault%3E) were run and

  - [ ] Onprem-AWS (link to job: )
  - [] Onprem-GCE (link to job: )

2018-06-08 23:46 UTC, cprovencher commented
the aws test failed, but it is related to the install prereqs script itself I believe not working for cent-os-7.This PR fixes the issue where that script could not even be invoqued.

2018-06-09 00:12 UTC, orsenthil approved these changes
LGTM.

(We can try the other PR which fixes the install-prereqs.sh (https://github.com/dcos/dcos-launch/pull/146)  and see that succeeds).

2018-06-11 17:20 UTC, margaret commented
I'm currently looking at it, but it seems like the onprem-AWS test was passing on the master branch as of 9 days ago. Can you be more specific about what's different on this PR that made it fail?

2018-06-11 17:25 UTC, margaret commented
Also, instead of deleting stuff from the PR template I think it would be better to do strikethrough and explain why it isn't relevant to the PR

2018-06-11 17:37 UTC, cprovencher commented
@margaret  Sure -  I used a temporary config to run that integration test. It's not the same as the one that runs and has been passing on master. I put the field "install_prereqs: True" which used to crash dcos-launch, but as we can see in this test, the install_prereqs script gets triggered successfully. However there might be something missing in the prereqs script itself to make DC/OS work with centos-7. I can just retrigger this with the cent-os-7 prereqs os instead of cent-os-7 and it will pass

2018-06-11 17:43 UTC, margaret requested changes
Can you add a test in `test_onprem.py` that checks that it does actually grab the right file?

2018-06-14 01:11 UTC, margaret approved these changes
👍

2018-06-14 01:22 UTC, merged