Allow for setting minCpuPlatform in GCP.
dcos/dcos-launch pull request #181
Opened 2018-09-30 21:46 UTC by bmcstdio

## High-level description (required)

To launch GCP instances with more than 64 CPUs or 445GB RAM, one must specify `Intel Skylake` as the (minimum) CPU platform. This PR adds support for optionally choosing a minimum CPU platform. This is useful, for instance, when launching big clusters for scale testing.

## Corresponding tickets (required)

N/A

## Related tickets (optional)

N/A

## Related PRs (optional)

N/A

## Checklist for all PRs

  - [ ] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: N/A
  - [X] **Added or updated any relevant documentation**

[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch&branch_DcosIo_DcosLaunch=%3Cdefault%3E) were run and

  - [ ] AWS Cloudformation Simple (link to job: )
  - [ ] Azure Resource Manager (link to job: )
  - [ ] Onprem-AWS (link to job: )
  - [ ] Onprem-GCE (link to job: )

**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs should have two approved [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner.

2018-09-30 21:47 UTC, bmcstdio commented
@cprovencher @margaret

2018-10-01 23:45 UTC, cprovencher requested changes
Config option should be in snake case, other than that it looks good. I'll run the GCP integration test against it once the change has been committed.

2018-10-01 23:45 UTC, cprovencher commented on dcos_launch/config.py
> +    'minCpuPlatform': {
Should be in snake case

2018-10-01 23:49 UTC, bmcstdio commented on dcos_launch/config.py
> +    'minCpuPlatform': {
@cprovencher done!

2021-05-03 11:17 UTC, closed without merging